### ISSUE TITLE
Adding Tab to TabPane throws NPE

### ISSUE THREAD

**Issue by jperedadnr** [gluonhq/scenebuilder#235]
When adding a `Tab` to a `TabPane`, Scene Builder throws a NPE at

At `com.oracle.javafx.scenebuilder.kit.editor.panel.content.ContentPanelController::reveal`:
```
final Tab tab = (Tab) sceneGraphObject;
final TabPane tabPane = tab.getTabPane();
tabPane.getSelectionModel().select(tab);
```

```
com.oracle.javafx.scenebuilder.kit.editor.panel.util.AbstractPanelController lambda$new$5
SEVERE: Bug
java.lang.NullPointerException
	at com.oracle.javafx.scenebuilder.kit.editor.panel.content.ContentPanelController.reveal(ContentPanelController.java:417)
	at com.oracle.javafx.scenebuilder.kit.editor.panel.content.mode.EditModeController.makeSelectionVisible(EditModeController.java:226)
	at com.oracle.javafx.scenebuilder.kit.editor.panel.content.mode.EditModeController.editorSelectionDidChange(EditModeController.java:189)
	at com.oracle.javafx.scenebuilder.kit.editor.panel.content.ContentPanelController.editorSelectionDidChange(ContentPanelController.java:825)
	at com.oracle.javafx.scenebuilder.kit.editor.panel.util.AbstractPanelController.lambda$new$5(AbstractPanelController.java:232)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:360)
```

Probably caused because the tab doesn't have a tabPane yet

**Comment by AlmasB** [comment]
@jperedadnr could you point me to where I would get the `TabPane` from (I assume there is some scene graph object)?

**Comment by jperedadnr** [comment]
This is how you can reproduce the issue:

- Open SB, new empty template
- Drag a TabPane from Containers
- Drag a Tab from Containers into the TabPane. It seems nothing happens and the tab is added. However, if you click on the added tab you see it doesn't get selected. Only after clicking the other tabs, you can go back and select it.

Now if you open the logs you'll find out the reason:

```
Feb 22, 2022 8:34:13 PM com.oracle.javafx.scenebuilder.kit.editor.panel.util.AbstractPanelController lambda$new$5
SEVERE: Bug
java.lang.NullPointerException
	at com.oracle.javafx.scenebuilder.kit.editor.panel.content.ContentPanelController.reveal(ContentPanelController.java:419)
	at com.oracle.javafx.scenebuilder.kit.editor.panel.content.mode.EditModeController.makeSelectionVisible(EditModeController.java:230)
	at com.oracle.javafx.scenebuilder.kit.editor.panel.content.mode.EditModeController.editorSelectionDidChange(EditModeController.java:190)
	at com.oracle.javafx.scenebuilder.kit.editor.panel.content.ContentPanelController.editorSelectionDidChange(ContentPanelController.java:828)
	at com.oracle.javafx.scenebuilder.kit.editor.panel.util.AbstractPanelController.lambda$new$5(AbstractPanelController.java:232)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:360)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.base/javafx.beans.property.IntegerPropertyBase.fireValueChangedEvent(IntegerPropertyBase.java:107)
```

Another way to see it: add `x.printStackTrace()` in `com.oracle.javafx.scenebuilder.kit.editor.panel.util.AbstractPanelController::editorSelectionListener`:
```
private final ChangeListener<Number> editorSelectionListener = 
        (observable, oldValue, newValue) -> {
        try {
            editorSelectionDidChange();
        } catch(RuntimeException x) {
            x.printStackTrace();
            LOG.log(Level.SEVERE, "Bug", x); //NOI18N
        }
    };
```

Build, and run the above again, you should see now when dragging the Tab:
```
java.lang.NullPointerException
        at com.oracle.javafx.scenebuilder.kit.editor.panel.content.ContentPanelController.reveal(ContentPanelController.java:419)
        at com.oracle.javafx.scenebuilder.kit.editor.panel.content.mode.EditModeController.makeSelectionVisible(EditModeController.java:230)
        at com.oracle.javafx.scenebuilder.kit.editor.panel.content.mode.EditModeController.editorSelectionDidChange(EditModeController.java:190)
        at com.oracle.javafx.scenebuilder.kit.editor.panel.content.ContentPanelController.editorSelectionDidChange(ContentPanelController.java:828)
        at com.oracle.javafx.scenebuilder.kit.editor.panel.util.AbstractPanelController.lambda$new$5(AbstractPanelController.java:233)
        at javafx.base/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:360)
        at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
        at javafx.base/javafx.beans.property.IntegerPropertyBase.fireValueChangedEvent(IntegerPropertyBase.java:107)
        at javafx.base/javafx.beans.property.IntegerPropertyBase.markInvalid(IntegerPropertyBase.java:114)
        at javafx.base/javafx.beans.property.IntegerPropertyBase.set(IntegerPropertyBase.java:148)
        at com.oracle.javafx.scenebuilder.kit.editor.selection.Selection.incrementRevision(Selection.java:506)
        at com.oracle.javafx.scenebuilder.kit.editor.selection.Selection.endUpdate(Selection.java:454)
        at com.oracle.javafx.scenebuilder.kit.editor.job.BatchJob.execute(BatchJob.java:128)
        at com.oracle.javafx.scenebuilder.kit.editor.job.reference.UpdateReferencesJob.execute(UpdateReferencesJob.java:78)
        at com.oracle.javafx.scenebuilder.kit.editor.JobManager.executeJob(JobManager.java:193)
        at com.oracle.javafx.scenebuilder.kit.editor.JobManager.push(JobManager.java:82)
        at com.oracle.javafx.scenebuilder.kit.editor.drag.DragController.end(DragController.java:127)
        at com.oracle.javafx.scenebuilder.kit.editor.panel.library.LibraryPanelController.lambda$startListeningToDrop$9(LibraryPanelController.java:653)
 ```

As I mentioned in the bug, `tab.getTabPane()` returns null and `tabPane.getSelectionModel().select(tab);` produces that NPE.

Note also that there is an [`assert`](https://github.com/gluonhq/scenebuilder/blob/master/kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/panel/content/ContentPanelController.java#L416), but we don't run with asserts enabled.

So another way to find the exception is enabling assertions:
```
<plugin>
                    <groupId>org.openjfx</groupId>
                    <artifactId>javafx-maven-plugin</artifactId>
                    <version>0.0.5</version>
                    <configuration>
                        <mainClass>${main.class.name}</mainClass>
                        <options>
                            <option>--add-opens=javafx.fxml/javafx.fxml=ALL-UNNAMED</option>
                            <option>-ea</option>
                        </options>
                    </configuration>
                </plugin>
```

now running the same will give:
```
java.lang.AssertionError
        at com.oracle.javafx.scenebuilder.kit.editor.panel.content.ContentPanelController.reveal(ContentPanelController.java:417)
        at com.oracle.javafx.scenebuilder.kit.editor.panel.content.mode.EditModeController.makeSelectionVisible(EditModeController.java:230)
        at com.oracle.javafx.scenebuilder.kit.editor.panel.content.mode.EditModeController.editorSelectionDidChange(EditModeController.java:190)
        at com.oracle.javafx.scenebuilder.kit.editor.panel.content.ContentPanelController.editorSelectionDidChange(ContentPanelController.java:828)
        at com.oracle.javafx.scenebuilder.kit.editor.panel.util.AbstractPanelController.lambda$new$5(AbstractPanelController.java:233)
```

As a possible fix, adding a null check will prevent the exception in the first place:

```
if (tabPane != null) {
                    tabPane.getSelectionModel().select(tab);
                }
```

but that won't solve the selection issue...

**Comment by AlmasB** [comment]
```
if (fxomObject.getParentObject().getSceneGraphObject() instanceof TabPane) {
    TabPane tabPane = (TabPane) fxomObject.getParentObject().getSceneGraphObject();
    tabPane.getSelectionModel().select((Tab) sceneGraphObject);
}
```

solves the NPE, but I don't know where to start on the selection issue
