### ISSUE TITLE
ArrayIndexOutOfBoundsException when right clicking

### ISSUE THREAD

**Issue by maroc81** [gluonhq/scenebuilder#247]
I hit the exception below when right clicking in the document hierarchy in scene builder.  Looking at the stack trace I could see it was something to do with the clipboard.  I copied some text, restarted scene builder, and then right click started working again.

I'm not sure what was on my clipboard but whatever it was caused this exception.  Details of my Scene Builder setup:

```
Product Version
JavaFX Scene Builder 11.0.0

Build Information
Version 11.0.0
Date: 2019-03-19
Java Version: 11.0.1+13-LTS, Oracle Corporation

Logging
The default configuration stores logging output in a file named scenebuilder-11.0.0.log (possibly followed by a trailing '.' and a digit).
The default file path is /tmp/scenebuilder-11.0.0.log

Java
11.0.1+13-LTS, Oracle Corporation

Operating System
Linux, amd64, 4.15.0-51-generic

Copyright (c) 2015-2018, Gluon.
```

I will update with additional information if I can reproduce.

```
Jun 13, 2019 7:37:00 PM com.oracle.javafx.scenebuilder.app.SceneBuilderApp$SceneBuilderUncaughtExceptionHandler uncaughtException
SEVERE: An exception was thrown:
java.lang.ArrayIndexOutOfBoundsException: 1
	at javafx.graphics/com.sun.glass.ui.gtk.GtkSystemClipboard.popFromSystem(Native Method)
	at javafx.graphics/com.sun.glass.ui.SystemClipboard.getData(SystemClipboard.java:76)
	at javafx.graphics/com.sun.glass.ui.ClipboardAssistance.getData(ClipboardAssistance.java:95)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumClipboard.getContent(QuantumClipboard.java:295)
	at javafx.graphics/javafx.scene.input.Clipboard.getContentImpl(Clipboard.java:284)
	at javafx.graphics/javafx.scene.input.Clipboard.getContent(Clipboard.java:277)
	at javafx.graphics/javafx.scene.input.Clipboard.getFiles(Clipboard.java:420)
	at com.oracle.javafx.scenebuilder.kit.metadata.util.ClipboardDecoder.decode(ClipboardDecoder.java:100)
	at com.oracle.javafx.scenebuilder.kit.editor.job.PasteJob.makeSubJobs(PasteJob.java:73)
	at com.oracle.javafx.scenebuilder.kit.editor.job.BatchDocumentJob.getSubJobs(BatchDocumentJob.java:56)
	at com.oracle.javafx.scenebuilder.kit.editor.job.BatchDocumentJob.isExecutable(BatchDocumentJob.java:64)
	at com.oracle.javafx.scenebuilder.kit.editor.EditorController.canPerformEditAction(EditorController.java:1401)
	at com.oracle.javafx.scenebuilder.kit.editor.util.ContextMenuController$EditActionController.canPerform(ContextMenuController.java:534)
	at com.oracle.javafx.scenebuilder.kit.editor.util.ContextMenuController.handleOnShowing(ContextMenuController.java:226)
	at com.oracle.javafx.scenebuilder.kit.editor.util.ContextMenuController.lambda$new$1(ContextMenuController.java:128)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.stage.Window.fireEvent(Window.java:1368)
	at javafx.graphics/javafx.stage.Window$12.invalidated(Window.java:1058)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
	at javafx.graphics/javafx.stage.Window.setShowing(Window.java:1174)
	at javafx.graphics/javafx.stage.Window.show(Window.java:1189)
	at javafx.graphics/javafx.stage.PopupWindow.showImpl(PopupWindow.java:472)
	at javafx.graphics/javafx.stage.PopupWindow.show(PopupWindow.java:437)
	at javafx.controls/javafx.scene.control.ContextMenu.doShow(ContextMenu.java:320)
	at javafx.controls/javafx.scene.control.ContextMenu.show(ContextMenu.java:282)
	at javafx.controls/javafx.scene.control.Control.lambda$static$0(Control.java:199)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.scene.Scene.processMenuEvent(Scene.java:1889)
	at javafx.graphics/javafx.scene.Scene.access$4400(Scene.java:172)
	at javafx.graphics/javafx.scene.Scene$ScenePeerListener.menuEvent(Scene.java:2610)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMenuEvent$3(GlassViewEventHandler.java:471)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMenuEvent$4(GlassViewEventHandler.java:451)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:390)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMenuEvent(GlassViewEventHandler.java:450)
	at javafx.graphics/com.sun.glass.ui.View.handleMenuEvent(View.java:564)
	at javafx.graphics/com.sun.glass.ui.View.notifyMenu(View.java:894)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:834)

Jun 13, 2019 7:37:00 PM com.oracle.javafx.scenebuilder.app.SceneBuilderApp$SceneBuilderUncaughtExceptionHandler uncaughtException
SEVERE: An exception was thrown:
java.lang.NullPointerException
	at java.base/java.io.File.<init>(File.java:276)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumClipboard.getContent(QuantumClipboard.java:300)
	at javafx.graphics/javafx.scene.input.Clipboard.getContentImpl(Clipboard.java:284)
	at javafx.graphics/javafx.scene.input.Clipboard.getContent(Clipboard.java:277)
	at javafx.graphics/javafx.scene.input.Clipboard.getFiles(Clipboard.java:420)
	at com.oracle.javafx.scenebuilder.kit.metadata.util.ClipboardDecoder.decode(ClipboardDecoder.java:100)
	at com.oracle.javafx.scenebuilder.kit.editor.job.PasteJob.makeSubJobs(PasteJob.java:73)
	at com.oracle.javafx.scenebuilder.kit.editor.job.BatchDocumentJob.getSubJobs(BatchDocumentJob.java:56)
	at com.oracle.javafx.scenebuilder.kit.editor.job.BatchDocumentJob.isExecutable(BatchDocumentJob.java:64)
	at com.oracle.javafx.scenebuilder.kit.editor.EditorController.canPerformEditAction(EditorController.java:1401)
	at com.oracle.javafx.scenebuilder.kit.editor.util.ContextMenuController$EditActionController.canPerform(ContextMenuController.java:534)
	at com.oracle.javafx.scenebuilder.kit.editor.util.ContextMenuController.handleOnShowing(ContextMenuController.java:226)
	at com.oracle.javafx.scenebuilder.kit.editor.util.ContextMenuController.lambda$new$1(ContextMenuController.java:128)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.stage.Window.fireEvent(Window.java:1368)
	at javafx.graphics/javafx.stage.Window$12.invalidated(Window.java:1058)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
	at javafx.graphics/javafx.stage.Window.setShowing(Window.java:1174)
	at javafx.graphics/javafx.stage.Window.show(Window.java:1189)
	at javafx.graphics/javafx.stage.PopupWindow.showImpl(PopupWindow.java:472)
	at javafx.graphics/javafx.stage.PopupWindow.show(PopupWindow.java:437)
	at javafx.controls/javafx.scene.control.ContextMenu.doShow(ContextMenu.java:320)
	at javafx.controls/javafx.scene.control.ContextMenu.show(ContextMenu.java:282)
	at javafx.controls/javafx.scene.control.Control.lambda$static$0(Control.java:199)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.scene.Scene.processMenuEvent(Scene.java:1889)
	at javafx.graphics/javafx.scene.Scene.access$4400(Scene.java:172)
	at javafx.graphics/javafx.scene.Scene$ScenePeerListener.menuEvent(Scene.java:2610)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMenuEvent$3(GlassViewEventHandler.java:471)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMenuEvent$4(GlassViewEventHandler.java:451)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:390)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMenuEvent(GlassViewEventHandler.java:450)
	at javafx.graphics/com.sun.glass.ui.View.handleMenuEvent(View.java:564)
	at javafx.graphics/com.sun.glass.ui.View.notifyMenu(View.java:894)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by maroc81** [comment]
I was able to reproduce this.  I have a Windows 7 VM running under VMware workstation.  If I copy a file in the VM then right click in Scene Builder, this exception is thrown.
