### ISSUE TITLE
Exceptions updating Intellij integration from 8.2.0 to 10/11

### ISSUE THREAD

**Issue by sirgl** [gluonhq/scenebuilder#252]
I'm trying to update dependencies to make Intellij IDEA's integration plugin work (https://youtrack.jetbrains.com/issue/IDEA-209562) on JDK 11 and ran into problems.
I tried to add dependency on charm-glisten.jar with different versions and failed to run it due to different exceptions.
With dependency on charm-glisten-6.0.1.jar I get:
```
java.lang.ExceptionInInitializerError
	at com.oracle.javafx.scenebuilder.kit.editor.EditorPlatform.<clinit>(EditorPlatform.java:105)
	at com.oracle.javafx.scenebuilder.kit.editor.EditorController.<init>(EditorController.java:271)
	at org.jetbrains.plugins.javaFX.sceneBuilder.AbstractSceneBuilderEditor.create(AbstractSceneBuilderEditor.java:115)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
Caused by: java.lang.NullPointerException
	at com.gluonhq.impl.charm.glisten.util.StylesheetTools.asResource(StylesheetTools.java:93)
	at com.gluonhq.charm.glisten.visual.GlistenStyleClasses.impl_loadResource(GlistenStyleClasses.java:97)
	at com.oracle.javafx.scenebuilder.kit.editor.EditorPlatform$Theme.<clinit>(EditorPlatform.java:125)
	... 7 more
```
but with charm-glisten-5.0.0-jdk9.jar (which is written in build.gradle) I get:
```
java.lang.Error: factory already defined
	at java.base/java.net.URL.setURLStreamHandlerFactory(URL.java:1184)
	at com.gluonhq.impl.charm.glisten.util.StylesheetTools.init(StylesheetTools.java:53)
	at com.gluonhq.charm.glisten.visual.GlistenStyleClasses.impl_loadResource(GlistenStyleClasses.java:94)
	at com.oracle.javafx.scenebuilder.kit.editor.EditorPlatform$Theme.<clinit>(EditorPlatform.java:125)
	at com.oracle.javafx.scenebuilder.kit.editor.EditorPlatform.<clinit>(EditorPlatform.java:105)
	at com.oracle.javafx.scenebuilder.kit.editor.EditorController.<init>(EditorController.java:271)
	at org.jetbrains.plugins.javaFX.sceneBuilder.AbstractSceneBuilderEditor.create(AbstractSceneBuilderEditor.java:115)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
```
Are there additional resources or libs required?

**Comment by tcfurrer** [comment]
Apparently this issue is blocking https://youtrack.jetbrains.com/issue/IDEA-209562, which has a lot of votes (and more almost every day).  Please give this issue the appropriate priority.

**Comment by abhinayagarwal** [comment]
@sirgl Is there a test case or an easy way to reproduce the exception?

**Comment by akozlova** [comment]
Run the following test
```
import com.oracle.javafx.scenebuilder.kit.editor.EditorController;
import org.junit.Test;

public class MyTest {
    @Test
    public void init() {
        new EditorController();
    }
}
```
in a project with dependency on junit, scenebuilder-kit-11.0.0.jar and javafx only. You get 
```
java.lang.NoClassDefFoundError: com/gluonhq/charm/glisten/control/AppBar

        at com.oracle.javafx.scenebuilder.kit.library.BuiltinLibrary.<init>(BuiltinLibrary.java:124)
	at com.oracle.javafx.scenebuilder.kit.library.BuiltinLibrary.getLibrary(BuiltinLibrary.java:88)
	at com.oracle.javafx.scenebuilder.kit.editor.EditorController.<init>(EditorController.java:266)
	at foo.MyTest.init(MyTest.java:8)
```

**Comment by jperedadnr** [comment]
The Kit is not a fat jar, so you'll need to include (some of) the dependencies that are listed here:

https://github.com/gluonhq/scenebuilder/blob/master/build.gradle#L40

At least, add Gluon Charm, the `org.eclipse.aether` dependencies won't be necessary probably.
