### ISSUE TITLE
Duplicating a table column crashes SceneBuilder

### ISSUE THREAD

**Issue by fotocyte** [gluonhq/scenebuilder#274]
To replicate: create a new scene, add an anchor pane, add a tableview, right-click the column in the tableview, select duplicate, then crash.

**Comment by nylanderdev** [comment]
Note: This only seems to crash SceneBuilder when launched from IntelliJ IDEA (Ultimate in my case, Community untested).

**Comment by Oliver-Loeffler** [comment]
To encircle the possible error I attempted to reproduce the error. As of now, I was not able to successfully reproduce the issue.
Could you pleas provide more boundary conditiosn?

Which Java version?
Which SceneBuilder version?
Was it the SceneBuilder provided by IDEA or was the SceneBuilder separately provided and configured in Idea accordingly?
Is it possible to reproduce using a provided FXML file?

Tested with:
| Version | OS | Package | Java Runtime | Observation |
|-|-|-|-|-|
|      8.5 | Windows 10 | Standalone   | 1.8.0_171-b11, Oracle Corporation | works, no crash |
| 15.0.1 | Windows 10 | MSI Installer | 15.0.2+7, AdoptOpenJDK | works, no crash |
| 11 | Windows 10 | IntelliJ 2020.1 Ultimate, 201.6668.121 | 11.0.6+8-b765.25 amd64, JetBrains | works, no crash |

**Comment by m-i-k-e-e** [comment]
Hi, 

I managed to reproduce it by launching scene builder from IntelliJ coummunity edition 2020.2

Product Version
JavaFX Scene Builder 11.0.0

Build Information
Version 11.0.0
Date: 2019-03-19
Java Version: 11.0.1+13-LTS, Oracle Corporation

Java
11.0.1+13-LTS, Oracle Corporation

Operating System
Linux, amd64, 5.9.13-100.fc32.x86_64

Copyright (c) 2015-2018, Gluon.

**Comment by ajinzrathod** [comment]
Is the issue solved?
This problem is reproduced here. 
BTW, I am using NetBeans and still this occured.

**Comment by Oliver-Loeffler** [comment]
Well, If it reproduces in Linux, I will also try again and also try to catch the thing with the debugger.

**Comment by AlmasB** [comment]
Reproduced on Windows 10 with latest SB build:

```
java.lang.NullPointerException: Cannot invoke "javafx.scene.control.TableView.getSkin()" because the return value of "javafx.scene.control.TableColumn.getTableView()" is null
	at javafx.scene.control.TableColumn.getStyleableNode(TableColumn.java:646)
	at com.oracle.javafx.scenebuilder.kit.util.CssInternal.getCssInfo(CssInternal.java:304)
	at com.oracle.javafx.scenebuilder.kit.editor.panel.inspector.InspectorPanelController.setEditorValueFromSelection(InspectorPanelController.java:1306)
	at com.oracle.javafx.scenebuilder.kit.editor.panel.inspector.InspectorPanelController.setEditorValueFromSelection(InspectorPanelController.java:1252)
	at com.oracle.javafx.scenebuilder.kit.editor.panel.inspector.InspectorPanelController.reset(InspectorPanelController.java:624)
	at com.oracle.javafx.scenebuilder.kit.editor.panel.inspector.InspectorPanelController.updateInspector(InspectorPanelController.java:541)
	at com.oracle.javafx.scenebuilder.kit.editor.panel.inspector.InspectorPanelController.editorSelectionDidChange(InspectorPanelController.java:463)
	at com.oracle.javafx.scenebuilder.kit.editor.panel.util.AbstractPanelController.lambda$new$5(AbstractPanelController.java:232)
```

**Comment by Oliver-Loeffler** [comment]
I cannot duplicate this using Scene Builder 19 on macOS 12.0.1.
