### ISSUE TITLE
Build error `module javafx.fxml does not "opens javafx.fxml" to unnamed module @2f490758`

### ISSUE THREAD

**Issue by SamuelWolfang** [gluonhq/scenebuilder#393]
I was trying to build scenebuilder on my M1 Macbook so that it could run natively.

Using Liberica with JavaFX (arm native)
```
Apache Maven 3.8.1 (Don't know if this is sensitive or not so I removed it)
Maven home: /opt/homebrew/Cellar/maven/3.8.1/libexec
Java version: 16.0.2, vendor: BellSoft, runtime: /Library/Java/JavaVirtualMachines/liberica-jdk-16-full.jdk/Contents/Home
Default locale: it_IT, platform encoding: UTF-8
OS name: "mac os x", version: "11.5.2", arch: "aarch64", family: "mac"
```

### What I tried
Looking online only thing I could find is `--module-path` and `--add-modules`.
Under `<plugins>` in the pom.xml file (root directory) I tried adding those commands separately:

```
<options>
   <option>--module-path=/Library/Java/JavaVirtualMachines/liberica-jdk-16-full.jdk/Contents/Home/lib</option>
   <option>--add-modules=javafx.web,javafx.fxml,javafx.swing,javafx.media</option>
   <option>--add-opens=javafx.fxml/javafx.fxml=ALL-UNNAMED</option>
</options>
```
 With no avail.
I tried running
`java --module-path /Library/Java/JavaVirtualMachines/liberica-jdk-16-full.jdk/Contents/Home/lib --add-modules javafx.web,javafx.fxml,javafx.swing,javafx.media --add-opens=javafx.fxml/javafx.fxml=ALL-UNNAMED -cp app/target/lib/scenebuilder-$version.jar com.oracle.javafx.scenebuilder.app.SceneBuilderApp`

but I get this error:
```
Error occurred during initialization of boot layer
java.lang.LayerInstantiationException: Package jdk.internal.jimage in both module jrt.fs and module java.base
```
I tried replacing `$version` with `16.0.0`, adding quotation marks between the modules in add-modules, but still same error.  I'm kind of frustrated at this point.

Here's the complete log:

```
samuelec@Air-di-Samu scenebuilder % mvn clean package    
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] Scene Builder                                                      [pom]
[INFO] Scene Builder Kit                                                  [jar]
[INFO] Scene Builder App                                                  [jar]
[INFO] 
[INFO] ------------------< com.gluonhq.scenebuilder:parent >-------------------
[INFO] Building Scene Builder 16.0.0-SNAPSHOT                             [1/3]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ parent ---
[INFO] 
[INFO] --------------------< com.gluonhq.scenebuilder:kit >--------------------
[INFO] Building Scene Builder Kit 16.0.0-SNAPSHOT                         [2/3]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ kit ---
[INFO] Deleting /Users/samuelec/Downloads/scenebuilder/kit/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ kit ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 569 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ kit ---
[INFO] Compiling 651 source files to /Users/samuelec/Downloads/scenebuilder/kit/target/classes
[INFO] /Users/samuelec/Downloads/scenebuilder/kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/glue/GlueLoader.java: /Users/samuelec/Downloads/scenebuilder/kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/glue/GlueLoader.java uses or overrides a deprecated API.
[INFO] /Users/samuelec/Downloads/scenebuilder/kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/glue/GlueLoader.java: Recompile with -Xlint:deprecation for details.
[INFO] /Users/samuelec/Downloads/scenebuilder/kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/panel/inspector/editors/DurationEditor.java: Some input files use unchecked or unsafe operations.
[INFO] /Users/samuelec/Downloads/scenebuilder/kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/panel/inspector/editors/DurationEditor.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ kit ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 30 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ kit ---
[INFO] Compiling 16 source files to /Users/samuelec/Downloads/scenebuilder/kit/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ kit ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.oracle.javafx.scenebuilder.kit.util.eventnames.FindEventNamesUtilTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.052 s - in com.oracle.javafx.scenebuilder.kit.util.eventnames.FindEventNamesUtilTest
[INFO] Running com.oracle.javafx.scenebuilder.kit.skeleton.SkeletonBufferKotlinTest
[ERROR] Tests run: 4, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 0.165 s <<< FAILURE! - in com.oracle.javafx.scenebuilder.kit.skeleton.SkeletonBufferKotlinTest
[ERROR] com.oracle.javafx.scenebuilder.kit.skeleton.SkeletonBufferKotlinTest.skeletonToString_testFxml_full_withComments  Time elapsed: 0.13 s  <<< ERROR!
java.lang.reflect.InaccessibleObjectException: Unable to make void javafx.fxml.FXMLLoader.setStaticLoad(boolean) accessible: module javafx.fxml does not "opens javafx.fxml" to unnamed module @2f490758
	at com.oracle.javafx.scenebuilder.kit.skeleton.SkeletonBufferKotlinTest.load(SkeletonBufferKotlinTest.java:123)
	at com.oracle.javafx.scenebuilder.kit.skeleton.SkeletonBufferKotlinTest.skeletonToString_testFxml_full_withComments(SkeletonBufferKotlinTest.java:70)

[ERROR] com.oracle.javafx.scenebuilder.kit.skeleton.SkeletonBufferKotlinTest.skeletonToString_testFxml_fullFormat  Time elapsed: 0.001 s  <<< ERROR!
java.lang.reflect.InaccessibleObjectException: Unable to make void javafx.fxml.FXMLLoader.setStaticLoad(boolean) accessible: module javafx.fxml does not "opens javafx.fxml" to unnamed module @2f490758
	at com.oracle.javafx.scenebuilder.kit.skeleton.SkeletonBufferKotlinTest.load(SkeletonBufferKotlinTest.java:123)
	at com.oracle.javafx.scenebuilder.kit.skeleton.SkeletonBufferKotlinTest.skeletonToString_testFxml_fullFormat(SkeletonBufferKotlinTest.java:97)

[ERROR] com.oracle.javafx.scenebuilder.kit.skeleton.SkeletonBufferKotlinTest.skeletonToString_nestedTestFxml  Time elapsed: 0.001 s  <<< ERROR!
java.lang.reflect.InaccessibleObjectException: Unable to make void javafx.fxml.FXMLLoader.setStaticLoad(boolean) accessible: module javafx.fxml does not "opens javafx.fxml" to unnamed module @2f490758
	at com.oracle.javafx.scenebuilder.kit.skeleton.SkeletonBufferKotlinTest.load(SkeletonBufferKotlinTest.java:123)
	at com.oracle.javafx.scenebuilder.kit.skeleton.SkeletonBufferKotlinTest.skeletonToString_nestedTestFxml(SkeletonBufferKotlinTest.java:58)

[ERROR] com.oracle.javafx.scenebuilder.kit.skeleton.SkeletonBufferKotlinTest.skeletonToString_testFxml_withComments  Time elapsed: 0.001 s  <<< ERROR!
java.lang.reflect.InaccessibleObjectException: Unable to make void javafx.fxml.FXMLLoader.setStaticLoad(boolean) accessible: module javafx.fxml does not "opens javafx.fxml" to unnamed module @2f490758
	at com.oracle.javafx.scenebuilder.kit.skeleton.SkeletonBufferKotlinTest.load(SkeletonBufferKotlinTest.java:123)
	at com.oracle.javafx.scenebuilder.kit.skeleton.SkeletonBufferKotlinTest.skeletonToString_testFxml_withComments(SkeletonBufferKotlinTest.java:84)

[INFO] Running com.oracle.javafx.scenebuilder.kit.skeleton.SkeletonBufferTest
[ERROR] Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 0.134 s <<< FAILURE! - in com.oracle.javafx.scenebuilder.kit.skeleton.SkeletonBufferTest
[ERROR] com.oracle.javafx.scenebuilder.kit.skeleton.SkeletonBufferTest.testControllerWithSimplePackageName  Time elapsed: 0.1 s  <<< ERROR!
java.lang.reflect.InaccessibleObjectException: Unable to make void javafx.fxml.FXMLLoader.setStaticLoad(boolean) accessible: module javafx.fxml does not "opens javafx.fxml" to unnamed module @2f490758
	at com.oracle.javafx.scenebuilder.kit.skeleton.SkeletonBufferTest.load(SkeletonBufferTest.java:91)
	at com.oracle.javafx.scenebuilder.kit.skeleton.SkeletonBufferTest.testControllerWithSimplePackageName(SkeletonBufferTest.java:64)

[ERROR] com.oracle.javafx.scenebuilder.kit.skeleton.SkeletonBufferTest.testControllerWithAdvancedPackageName  Time elapsed: 0.001 s  <<< ERROR!
java.lang.reflect.InaccessibleObjectException: Unable to make void javafx.fxml.FXMLLoader.setStaticLoad(boolean) accessible: module javafx.fxml does not "opens javafx.fxml" to unnamed module @2f490758
	at com.oracle.javafx.scenebuilder.kit.skeleton.SkeletonBufferTest.load(SkeletonBufferTest.java:91)
	at com.oracle.javafx.scenebuilder.kit.skeleton.SkeletonBufferTest.testControllerWithAdvancedPackageName(SkeletonBufferTest.java:77)

[ERROR] com.oracle.javafx.scenebuilder.kit.skeleton.SkeletonBufferTest.testControllerWithoutPackageName  Time elapsed: 0.001 s  <<< ERROR!
java.lang.reflect.InaccessibleObjectException: Unable to make void javafx.fxml.FXMLLoader.setStaticLoad(boolean) accessible: module javafx.fxml does not "opens javafx.fxml" to unnamed module @2f490758
	at com.oracle.javafx.scenebuilder.kit.skeleton.SkeletonBufferTest.load(SkeletonBufferTest.java:91)
	at com.oracle.javafx.scenebuilder.kit.skeleton.SkeletonBufferTest.testControllerWithoutPackageName(SkeletonBufferTest.java:51)

[INFO] Running com.oracle.javafx.scenebuilder.kit.skeleton.SkeletonBufferJavaTest
[ERROR] Tests run: 4, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 0.145 s <<< FAILURE! - in com.oracle.javafx.scenebuilder.kit.skeleton.SkeletonBufferJavaTest
[ERROR] com.oracle.javafx.scenebuilder.kit.skeleton.SkeletonBufferJavaTest.skeletonToString_testFxml_full_withComments  Time elapsed: 0.109 s  <<< ERROR!
java.lang.reflect.InaccessibleObjectException: Unable to make void javafx.fxml.FXMLLoader.setStaticLoad(boolean) accessible: module javafx.fxml does not "opens javafx.fxml" to unnamed module @2f490758
	at com.oracle.javafx.scenebuilder.kit.skeleton.SkeletonBufferJavaTest.load(SkeletonBufferJavaTest.java:123)
	at com.oracle.javafx.scenebuilder.kit.skeleton.SkeletonBufferJavaTest.skeletonToString_testFxml_full_withComments(SkeletonBufferJavaTest.java:70)

[ERROR] com.oracle.javafx.scenebuilder.kit.skeleton.SkeletonBufferJavaTest.skeletonToString_testFxml_fullFormat  Time elapsed: 0.001 s  <<< ERROR!
java.lang.reflect.InaccessibleObjectException: Unable to make void javafx.fxml.FXMLLoader.setStaticLoad(boolean) accessible: module javafx.fxml does not "opens javafx.fxml" to unnamed module @2f490758
	at com.oracle.javafx.scenebuilder.kit.skeleton.SkeletonBufferJavaTest.load(SkeletonBufferJavaTest.java:123)
	at com.oracle.javafx.scenebuilder.kit.skeleton.SkeletonBufferJavaTest.skeletonToString_testFxml_fullFormat(SkeletonBufferJavaTest.java:97)

[ERROR] com.oracle.javafx.scenebuilder.kit.skeleton.SkeletonBufferJavaTest.skeletonToString_nestedTestFxml  Time elapsed: 0.001 s  <<< ERROR!
java.lang.reflect.InaccessibleObjectException: Unable to make void javafx.fxml.FXMLLoader.setStaticLoad(boolean) accessible: module javafx.fxml does not "opens javafx.fxml" to unnamed module @2f490758
	at com.oracle.javafx.scenebuilder.kit.skeleton.SkeletonBufferJavaTest.load(SkeletonBufferJavaTest.java:123)
	at com.oracle.javafx.scenebuilder.kit.skeleton.SkeletonBufferJavaTest.skeletonToString_nestedTestFxml(SkeletonBufferJavaTest.java:58)

[ERROR] com.oracle.javafx.scenebuilder.kit.skeleton.SkeletonBufferJavaTest.skeletonToString_testFxml_withComments  Time elapsed: 0.001 s  <<< ERROR!
java.lang.reflect.InaccessibleObjectException: Unable to make void javafx.fxml.FXMLLoader.setStaticLoad(boolean) accessible: module javafx.fxml does not "opens javafx.fxml" to unnamed module @2f490758
	at com.oracle.javafx.scenebuilder.kit.skeleton.SkeletonBufferJavaTest.load(SkeletonBufferJavaTest.java:123)
	at com.oracle.javafx.scenebuilder.kit.skeleton.SkeletonBufferJavaTest.skeletonToString_testFxml_withComments(SkeletonBufferJavaTest.java:84)

[INFO] Running com.oracle.javafx.scenebuilder.kit.fxom.CreateFxomInstanceFromIntrinsicTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.069 s - in com.oracle.javafx.scenebuilder.kit.fxom.CreateFxomInstanceFromIntrinsicTest
[INFO] Running com.oracle.javafx.scenebuilder.kit.fxom.StaticLoadTest
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.134 s <<< FAILURE! - in com.oracle.javafx.scenebuilder.kit.fxom.StaticLoadTest
[ERROR] com.oracle.javafx.scenebuilder.kit.fxom.StaticLoadTest.testStaticLoad  Time elapsed: 0.101 s  <<< ERROR!
java.lang.reflect.InaccessibleObjectException: Unable to make void javafx.fxml.FXMLLoader.setStaticLoad(boolean) accessible: module javafx.fxml does not "opens javafx.fxml" to unnamed module @2f490758
	at com.oracle.javafx.scenebuilder.kit.fxom.StaticLoadTest.testStaticLoad(StaticLoadTest.java:78)

[ERROR] com.oracle.javafx.scenebuilder.kit.fxom.StaticLoadTest.testStaticLoadWithoutEventHandler  Time elapsed: 0.001 s  <<< ERROR!
java.lang.reflect.InaccessibleObjectException: Unable to make void javafx.fxml.FXMLLoader.setStaticLoad(boolean) accessible: module javafx.fxml does not "opens javafx.fxml" to unnamed module @2f490758
	at com.oracle.javafx.scenebuilder.kit.fxom.StaticLoadTest.testStaticLoadWithoutEventHandler(StaticLoadTest.java:63)

[INFO] Running com.oracle.javafx.scenebuilder.kit.fxom.AddIntrinsicPropertyTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.064 s - in com.oracle.javafx.scenebuilder.kit.fxom.AddIntrinsicPropertyTest
[INFO] Running com.oracle.javafx.scenebuilder.kit.fxom.FXOMSaverUpdateImportInstructionsTest
[ERROR] Tests run: 12, Failures: 0, Errors: 11, Skipped: 0, Time elapsed: 0.092 s <<< FAILURE! - in com.oracle.javafx.scenebuilder.kit.fxom.FXOMSaverUpdateImportInstructionsTest
[ERROR] com.oracle.javafx.scenebuilder.kit.fxom.FXOMSaverUpdateImportInstructionsTest.testDuplicates  Time elapsed: 0.044 s  <<< ERROR!
java.lang.reflect.InaccessibleObjectException: Unable to make void javafx.fxml.FXMLLoader.setStaticLoad(boolean) accessible: module javafx.fxml does not "opens javafx.fxml" to unnamed module @2f490758
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMSaverUpdateImportInstructionsTest.setupFXOMDocument(FXOMSaverUpdateImportInstructionsTest.java:285)
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMSaverUpdateImportInstructionsTest.setupTestCase(FXOMSaverUpdateImportInstructionsTest.java:266)
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMSaverUpdateImportInstructionsTest.testDuplicates(FXOMSaverUpdateImportInstructionsTest.java:158)

[ERROR] com.oracle.javafx.scenebuilder.kit.fxom.FXOMSaverUpdateImportInstructionsTest.testWildcardsAndDuplicates  Time elapsed: 0.002 s  <<< ERROR!
java.lang.reflect.InaccessibleObjectException: Unable to make void javafx.fxml.FXMLLoader.setStaticLoad(boolean) accessible: module javafx.fxml does not "opens javafx.fxml" to unnamed module @2f490758
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMSaverUpdateImportInstructionsTest.setupFXOMDocument(FXOMSaverUpdateImportInstructionsTest.java:285)
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMSaverUpdateImportInstructionsTest.setupTestCase(FXOMSaverUpdateImportInstructionsTest.java:266)
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMSaverUpdateImportInstructionsTest.testWildcardsAndDuplicates(FXOMSaverUpdateImportInstructionsTest.java:171)

[ERROR] com.oracle.javafx.scenebuilder.kit.fxom.FXOMSaverUpdateImportInstructionsTest.testWithWildcard  Time elapsed: 0.002 s  <<< ERROR!
java.lang.reflect.InaccessibleObjectException: Unable to make void javafx.fxml.FXMLLoader.setStaticLoad(boolean) accessible: module javafx.fxml does not "opens javafx.fxml" to unnamed module @2f490758
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMSaverUpdateImportInstructionsTest.setupFXOMDocument(FXOMSaverUpdateImportInstructionsTest.java:285)
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMSaverUpdateImportInstructionsTest.setupTestCase(FXOMSaverUpdateImportInstructionsTest.java:266)
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMSaverUpdateImportInstructionsTest.testWithWildcard(FXOMSaverUpdateImportInstructionsTest.java:118)

[ERROR] com.oracle.javafx.scenebuilder.kit.fxom.FXOMSaverUpdateImportInstructionsTest.testWithMoreWildcards  Time elapsed: 0.002 s  <<< ERROR!
java.lang.reflect.InaccessibleObjectException: Unable to make void javafx.fxml.FXMLLoader.setStaticLoad(boolean) accessible: module javafx.fxml does not "opens javafx.fxml" to unnamed module @2f490758
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMSaverUpdateImportInstructionsTest.setupFXOMDocument(FXOMSaverUpdateImportInstructionsTest.java:285)
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMSaverUpdateImportInstructionsTest.setupTestCase(FXOMSaverUpdateImportInstructionsTest.java:266)
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMSaverUpdateImportInstructionsTest.testWithMoreWildcards(FXOMSaverUpdateImportInstructionsTest.java:131)

[ERROR] com.oracle.javafx.scenebuilder.kit.fxom.FXOMSaverUpdateImportInstructionsTest.testImportsWithComments  Time elapsed: 0.001 s  <<< ERROR!
java.lang.reflect.InaccessibleObjectException: Unable to make void javafx.fxml.FXMLLoader.setStaticLoad(boolean) accessible: module javafx.fxml does not "opens javafx.fxml" to unnamed module @2f490758
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMSaverUpdateImportInstructionsTest.setupFXOMDocument(FXOMSaverUpdateImportInstructionsTest.java:285)
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMSaverUpdateImportInstructionsTest.setupTestCase(FXOMSaverUpdateImportInstructionsTest.java:266)
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMSaverUpdateImportInstructionsTest.testImportsWithComments(FXOMSaverUpdateImportInstructionsTest.java:209)

[ERROR] com.oracle.javafx.scenebuilder.kit.fxom.FXOMSaverUpdateImportInstructionsTest.testWithGlueElements  Time elapsed: 0.002 s  <<< ERROR!
java.lang.reflect.InaccessibleObjectException: Unable to make void javafx.fxml.FXMLLoader.setStaticLoad(boolean) accessible: module javafx.fxml does not "opens javafx.fxml" to unnamed module @2f490758
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMSaverUpdateImportInstructionsTest.setupFXOMDocument(FXOMSaverUpdateImportInstructionsTest.java:285)
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMSaverUpdateImportInstructionsTest.setupTestCase(FXOMSaverUpdateImportInstructionsTest.java:266)
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMSaverUpdateImportInstructionsTest.testWithGlueElements(FXOMSaverUpdateImportInstructionsTest.java:145)

[ERROR] com.oracle.javafx.scenebuilder.kit.fxom.FXOMSaverUpdateImportInstructionsTest.testNoWildcard  Time elapsed: 0.001 s  <<< ERROR!
java.lang.reflect.InaccessibleObjectException: Unable to make void javafx.fxml.FXMLLoader.setStaticLoad(boolean) accessible: module javafx.fxml does not "opens javafx.fxml" to unnamed module @2f490758
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMSaverUpdateImportInstructionsTest.setupFXOMDocument(FXOMSaverUpdateImportInstructionsTest.java:285)
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMSaverUpdateImportInstructionsTest.setupTestCase(FXOMSaverUpdateImportInstructionsTest.java:266)
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMSaverUpdateImportInstructionsTest.testNoWildcard(FXOMSaverUpdateImportInstructionsTest.java:83)

[ERROR] com.oracle.javafx.scenebuilder.kit.fxom.FXOMSaverUpdateImportInstructionsTest.testWildcardsAndStaticProperties  Time elapsed: 0.001 s  <<< ERROR!
java.lang.reflect.InaccessibleObjectException: Unable to make void javafx.fxml.FXMLLoader.setStaticLoad(boolean) accessible: module javafx.fxml does not "opens javafx.fxml" to unnamed module @2f490758
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMSaverUpdateImportInstructionsTest.setupFXOMDocument(FXOMSaverUpdateImportInstructionsTest.java:285)
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMSaverUpdateImportInstructionsTest.setupTestCase(FXOMSaverUpdateImportInstructionsTest.java:266)
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMSaverUpdateImportInstructionsTest.testWildcardsAndStaticProperties(FXOMSaverUpdateImportInstructionsTest.java:230)

[ERROR] com.oracle.javafx.scenebuilder.kit.fxom.FXOMSaverUpdateImportInstructionsTest.testPublicStaticImport  Time elapsed: 0.002 s  <<< ERROR!
java.lang.reflect.InaccessibleObjectException: Unable to make void javafx.fxml.FXMLLoader.setStaticLoad(boolean) accessible: module javafx.fxml does not "opens javafx.fxml" to unnamed module @2f490758
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMSaverUpdateImportInstructionsTest.setupFXOMDocument(FXOMSaverUpdateImportInstructionsTest.java:285)
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMSaverUpdateImportInstructionsTest.setupTestCase(FXOMSaverUpdateImportInstructionsTest.java:266)
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMSaverUpdateImportInstructionsTest.testPublicStaticImport(FXOMSaverUpdateImportInstructionsTest.java:244)

[ERROR] com.oracle.javafx.scenebuilder.kit.fxom.FXOMSaverUpdateImportInstructionsTest.testCustomButton  Time elapsed: 0.001 s  <<< ERROR!
java.lang.reflect.InaccessibleObjectException: Unable to make void javafx.fxml.FXMLLoader.setStaticLoad(boolean) accessible: module javafx.fxml does not "opens javafx.fxml" to unnamed module @2f490758
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMSaverUpdateImportInstructionsTest.setupFXOMDocument(FXOMSaverUpdateImportInstructionsTest.java:285)
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMSaverUpdateImportInstructionsTest.setupTestCase(FXOMSaverUpdateImportInstructionsTest.java:266)
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMSaverUpdateImportInstructionsTest.testCustomButton(FXOMSaverUpdateImportInstructionsTest.java:188)

[ERROR] com.oracle.javafx.scenebuilder.kit.fxom.FXOMSaverUpdateImportInstructionsTest.testUnusedImports  Time elapsed: 0.001 s  <<< ERROR!
java.lang.reflect.InaccessibleObjectException: Unable to make void javafx.fxml.FXMLLoader.setStaticLoad(boolean) accessible: module javafx.fxml does not "opens javafx.fxml" to unnamed module @2f490758
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMSaverUpdateImportInstructionsTest.setupFXOMDocument(FXOMSaverUpdateImportInstructionsTest.java:285)
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMSaverUpdateImportInstructionsTest.setupTestCase(FXOMSaverUpdateImportInstructionsTest.java:266)
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMSaverUpdateImportInstructionsTest.testUnusedImports(FXOMSaverUpdateImportInstructionsTest.java:101)

[INFO] Running com.oracle.javafx.scenebuilder.kit.editor.panel.library.manager.DialogListItemComparatorTest
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.031 s - in com.oracle.javafx.scenebuilder.kit.editor.panel.library.manager.DialogListItemComparatorTest
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   FXOMSaverUpdateImportInstructionsTest.testCustomButton:188->setupTestCase:266->setupFXOMDocument:285 » InaccessibleObject
[ERROR]   FXOMSaverUpdateImportInstructionsTest.testDuplicates:158->setupTestCase:266->setupFXOMDocument:285 » InaccessibleObject
[ERROR]   FXOMSaverUpdateImportInstructionsTest.testImportsWithComments:209->setupTestCase:266->setupFXOMDocument:285 » InaccessibleObject
[ERROR]   FXOMSaverUpdateImportInstructionsTest.testNoWildcard:83->setupTestCase:266->setupFXOMDocument:285 » InaccessibleObject
[ERROR]   FXOMSaverUpdateImportInstructionsTest.testPublicStaticImport:244->setupTestCase:266->setupFXOMDocument:285 » InaccessibleObject
[ERROR]   FXOMSaverUpdateImportInstructionsTest.testUnusedImports:101->setupTestCase:266->setupFXOMDocument:285 » InaccessibleObject
[ERROR]   FXOMSaverUpdateImportInstructionsTest.testWildcardsAndDuplicates:171->setupTestCase:266->setupFXOMDocument:285 » InaccessibleObject
[ERROR]   FXOMSaverUpdateImportInstructionsTest.testWildcardsAndStaticProperties:230->setupTestCase:266->setupFXOMDocument:285 » InaccessibleObject
[ERROR]   FXOMSaverUpdateImportInstructionsTest.testWithGlueElements:145->setupTestCase:266->setupFXOMDocument:285 » InaccessibleObject
[ERROR]   FXOMSaverUpdateImportInstructionsTest.testWithMoreWildcards:131->setupTestCase:266->setupFXOMDocument:285 » InaccessibleObject
[ERROR]   FXOMSaverUpdateImportInstructionsTest.testWithWildcard:118->setupTestCase:266->setupFXOMDocument:285 » InaccessibleObject
[ERROR]   StaticLoadTest.testStaticLoad:78 » InaccessibleObject Unable to make void java...
[ERROR]   StaticLoadTest.testStaticLoadWithoutEventHandler:63 » InaccessibleObject Unabl...
[ERROR]   SkeletonBufferJavaTest.skeletonToString_nestedTestFxml:58->load:123 » InaccessibleObject
[ERROR]   SkeletonBufferJavaTest.skeletonToString_testFxml_fullFormat:97->load:123 » InaccessibleObject
[ERROR]   SkeletonBufferJavaTest.skeletonToString_testFxml_full_withComments:70->load:123 » InaccessibleObject
[ERROR]   SkeletonBufferJavaTest.skeletonToString_testFxml_withComments:84->load:123 » InaccessibleObject
[ERROR]   SkeletonBufferKotlinTest.skeletonToString_nestedTestFxml:58->load:123 » InaccessibleObject
[ERROR]   SkeletonBufferKotlinTest.skeletonToString_testFxml_fullFormat:97->load:123 » InaccessibleObject
[ERROR]   SkeletonBufferKotlinTest.skeletonToString_testFxml_full_withComments:70->load:123 » InaccessibleObject
[ERROR]   SkeletonBufferKotlinTest.skeletonToString_testFxml_withComments:84->load:123 » InaccessibleObject
[ERROR]   SkeletonBufferTest.testControllerWithAdvancedPackageName:77->load:91 » InaccessibleObject
[ERROR]   SkeletonBufferTest.testControllerWithSimplePackageName:64->load:91 » InaccessibleObject
[ERROR]   SkeletonBufferTest.testControllerWithoutPackageName:51->load:91 » InaccessibleObject
[INFO] 
[ERROR] Tests run: 36, Failures: 0, Errors: 24, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Scene Builder 16.0.0-SNAPSHOT:
[INFO] 
[INFO] Scene Builder ...................................... SUCCESS [  0.048 s]
[INFO] Scene Builder Kit .................................. FAILURE [  6.501 s]
[INFO] Scene Builder App .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.591 s
[INFO] Finished at: 2021-08-21T11:09:22+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project kit: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/samuelec/Downloads/scenebuilder/kit/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :kit
```
Here is the [surefire-reports folder](https://github.com/gluonhq/scenebuilder/files/7025248/surefire-reports.zip) in case you need it.

Thanks in advance!

**Comment by abhinayagarwal** [comment]
Hi @SamuelWolfang ,

Thank you for reporting the issue. 

`aarch64` artifacts for macos are now available in Maven Central since JavaFX 17. Since `master` branch already uses `17`, I would suggest to pull latest changes from master and then run:

```
mvn clean install && mvn javafx:run -f app
```
