### ISSUE TITLE
CheckUpdate functionality runs in wrong thread at the first call after app starts

### ISSUE THREAD

**Issue by Oliver-Loeffler** [gluonhq/scenebuilder#601]
When SceneBuilder is started first time and the the function `Menu -> Help\Check for update,,,` is called, there will be no dialog to indicate any action. Instead a stack trace like the following is produced.

The issue does not occur for repeated calls to `SceneBuilderApp.checkUpdates()` method.

```
Nov. 08, 2022 6:27:46 PM com.oracle.javafx.scenebuilder.app.SceneBuilderApp$SceneBuilderUncaughtExceptionHandler uncaughtException
SCHWERWIEGEND: An exception was thrown:
java.lang.IllegalStateException: Not on FX application thread; currentThread = GetLatestVersion
        at javafx.graphics@19/com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:299)
        at javafx.graphics@19/com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:458)
        at javafx.graphics@19/javafx.stage.Stage.<init>(Stage.java:258)
        at javafx.graphics@19/javafx.stage.Stage.<init>(Stage.java:244)
        at javafx.controls@19/javafx.scene.control.HeavyweightDialog$1.<init>(HeavyweightDialog.java:52)
        at javafx.controls@19/javafx.scene.control.HeavyweightDialog.<init>(HeavyweightDialog.java:52)
        at javafx.controls@19/javafx.scene.control.Dialog.<init>(Dialog.java:252)
        at javafx.controls@19/javafx.scene.control.Alert.<init>(Alert.java:247)
        at javafx.controls@19/javafx.scene.control.Alert.<init>(Alert.java:222)
        at com.oracle.javafx.scenebuilder.kit.alert.SBAlert.<init>(SBAlert.java:43)
        at com.oracle.javafx.scenebuilder.app.SceneBuilderApp.lambda$checkUpdates$20(SceneBuilderApp.java:1055)
        at com.oracle.javafx.scenebuilder.app.util.AppSettings.lambda$getLatestVersion$0(AppSettings.java:141)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

### Expected Behavior
* With a click on `Help\Check for update,,,`, SceneBuilder is expected to respond to the user

### Current Behavior
* With a click on `Help\Check for update,,,`, SceneBuilder does not show the requested dialog, instead an exception is thrown.
* With a repeated click on `Help\Check for update,,,` the expected dialog appears and no exception is thrown

### Steps to Reproduce
* on Windows 10:
    * clone Scene Builder
    * run the build
    * run the app
    * open any FXML or start over with empty template
    * Run: `Help\Check for update,,,`

### Your Environment
* Win10 21H2, Java 19, JavaFX 19, 
* Started with Maven on Windows Command Line

### Screenshots

![4](https://user-images.githubusercontent.com/22102800/200635562-9b4e7f52-9581-462b-a938-94c8e3fb4cca.png)

**Comment by Oliver-Loeffler** [comment]
Just found also that there was no release page for Scene Builder 19. The "Learn More" button in the check update dialog points always to a link such as https://gluonhq.com/scene-builder-19-release/. This exists for 17 and 18, not for 19.
