### ISSUE TITLE
NPE: InspectorPanelController.getExpandedSection() is null

### ISSUE THREAD

**Issue by jperedadnr** [gluonhq/scenebuilder#771]
### Steps to Reproduce

Open Scene Builder, empty template, go to Inspector MenuButton, and select View by property Name.
The exception is thrown:

```
SEVERE: An exception was thrown:
java.lang.NullPointerException: Cannot invoke "com.oracle.javafx.scenebuilder.kit.editor.panel.inspector.InspectorPanelController$SectionId.ordinal()" because the return value of "com.oracle.javafx.scenebuilder.kit.editor.panel.inspector.InspectorPanelController.getExpandedSection()" is null
        at com.gluonhq.scenebuilder.kit@24.0.0-SNAPSHOT/com.oracle.javafx.scenebuilder.kit.editor.panel.inspector.InspectorPanelController.expandedSectionChanged(InspectorPanelController.java:380)
        at com.gluonhq.scenebuilder.kit@24.0.0-SNAPSHOT/com.oracle.javafx.scenebuilder.kit.editor.panel.inspector.InspectorPanelController.lambda$new$2(InspectorPanelController.java:244)
        at javafx.base@23.0.1/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:192)
        at javafx.base@23.0.1/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:91)
        at javafx.base@23.0.1/javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:106)
        at javafx.base@23.0.1/javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:113)
        at javafx.base@23.0.1/javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:147)
        at javafx.base@23.0.1/javafx.beans.property.ObjectProperty.setValue(ObjectProperty.java:78)
        at com.gluonhq.scenebuilder.kit@24.0.0-SNAPSHOT/com.oracle.javafx.scenebuilder.kit.editor.panel.inspector.InspectorPanelController.lambda$controllerDidLoadFxml$10(InspectorPanelController.java:507)
        at javafx.base@23.0.1/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:386)
        at javafx.base@23.0.1/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:91)
        at javafx.base@23.0.1/javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:106)
        at javafx.base@23.0.1/javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:113)
        at javafx.base@23.0.1/javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:147)
        at javafx.controls@23.0.1/javafx.scene.control.Accordion.setExpandedPane(Accordion.java:178)
        at javafx.controls@23.0.1/javafx.scene.control.skin.AccordionSkin.lambda$expandedPropertyListener$3(AccordionSkin.java:330)
        at javafx.base@23.0.1/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:192)
        at javafx.base@23.0.1/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:91)
        at javafx.base@23.0.1/javafx.beans.property.BooleanPropertyBase.fireValueChangedEvent(BooleanPropertyBase.java:104)
        at javafx.base@23.0.1/javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:111)
        at javafx.base@23.0.1/javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
        at javafx.controls@23.0.1/javafx.scene.control.TitledPane.setExpanded(TitledPane.java:175)
        at com.gluonhq.scenebuilder.kit@24.0.0-SNAPSHOT/com.oracle.javafx.scenebuilder.kit.editor.panel.inspector.InspectorPanelController.viewModeChanged(InspectorPanelController.java:342)
        at com.gluonhq.scenebuilder.kit@24.0.0-SNAPSHOT/com.oracle.javafx.scenebuilder.kit.editor.panel.inspector.InspectorPanelController.lambda$new$0(InspectorPanelController.java:238)
        at javafx.base@23.0.1/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:192)
        at javafx.base@23.0.1/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:91)
        at javafx.base@23.0.1/javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:106)
        at javafx.base@23.0.1/javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:113)
        at javafx.base@23.0.1/javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:147)
        at javafx.base@23.0.1/javafx.beans.property.ObjectProperty.setValue(ObjectProperty.java:78)
        at com.gluonhq.scenebuilder.kit@24.0.0-SNAPSHOT/com.oracle.javafx.scenebuilder.kit.editor.panel.inspector.InspectorPanelController.setViewMode(InspectorPanelController.java:321)
        at com.gluonhq.scenebuilder.app@24.0.0-SNAPSHOT/com.oracle.javafx.scenebuilder.app.DocumentWindowController.onInspectorViewByPropertyNameAction(DocumentWindowController.java:1320)  
```

**Comment by abhinayagarwal** [comment]
I tried these steps but wasn't able to reproduce the exception from `master` branch:

> Open Scene Builder, empty template, go to Inspector MenuButton, and select View by property Name.

Is there a step that's missed here?

**Comment by jperedadnr** [comment]
See logs or add a ConsoleHandler to logging.properties
