### ISSUE TITLE
Exceptions and memory leak (possibly RTL issue)

### ISSUE THREAD

**Issue by gluon-bot** [gluonhq/scenebuilder#83]
Originally reported by: **Itai Shaked (Bitbucket: [itai_shaked](https://bitbucket.org/itai_shaked), GitHub: Unknown)**

----------------------------------------

Whenever using Scene Builder (8.2.0) to edit FXMLs with NodeOrientation set to Right-to-Left I'm getting multiple exceptions thrown, and memory usage quickly climbs to 5 GB or even more, making the entire system sluggish, until Scene Builder is restarted. 

Below are snippets of exceptions thrown: 

SEVERE: An exception was thrown:
java.lang.IndexOutOfBoundsException: Index: 6, Size: 6
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.oracle.javafx.scenebuilder.kit.editor.panel.content.driver.gridpane.GridPaneMosaic.getCellBounds(GridPaneMosaic.java:894)
	at com.oracle.javafx.scenebuilder.kit.editor.panel.content.driver.gridpane.GridPaneMosaic.updateTargetCell(GridPaneMosaic.java:882)
...

======

SEVERE: Bug
java.lang.NullPointerException
	at com.oracle.javafx.scenebuilder.kit.editor.panel.content.ContentPanelController.reveal(ContentPanelController.java:400)
	at com.oracle.javafx.scenebuilder.kit.editor.panel.content.mode.EditModeController.makeSelectionVisible(EditModeController.java:226)
	at com.oracle.javafx.scenebuilder.kit.editor.panel.content.mode.EditModeController.editorSelectionDidChange(EditModeController.java:189)

===

As the exceptions are only shown in the console I only notice it after a while when the program becomes unusually sluggish. If provided stack traces are not enough I can try to pin-point reproduction steps. 

----------------------------------------
- Bitbucket: https://bitbucket.org/gluon-oss/scenebuilder/issue/83

**Comment by AlmasB** [comment]
Possibly related to #235
